# Generated by Django 4.0.3 on 2022-03-28 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='currentListing',
        ),
        migrations.AddField(
            model_name='bid',
            name='currentListing',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='bidListing', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
